const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const root = path.join(__dirname, '..')
const script = path.join(root, 'scripts/audit-consolidation.mjs')

test('repository audit is read-only, detects local changes and preserves unrelated projects', () => {
  const source = fs.readFileSync(script, 'utf8')
  assert.match(source, /git\(dir, 'status'/)
  assert.match(source, /git\(dir, 'stash', 'list'/)
  assert.match(source, /git\(canonical, 'merge-base'/)
  assert.match(source, /unrelatedHistory: true/)
  assert.doesNotMatch(source, /spawnSync\([^\n]+(push|reset|checkout|clean|merge|rebase|delete)/)
  const run = spawnSync(process.execPath, [script], { cwd: root, encoding: 'utf8', timeout: 30000 })
  assert.equal(run.status, 0, run.stderr)
  const audit = JSON.parse(run.stdout)
  assert.equal(audit.canonical.available, true)
  assert.ok(audit.canonical.trackedFiles > 0)
  assert.ok(Array.isArray(audit.sources))
  assert.ok(Array.isArray(audit.remoteBranches))
  assert.ok(audit.rules.some(r => r.includes('verified functional parity')))
})
