const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const script = fs.readFileSync(path.join(__dirname, '../scripts/seed-shared-users.ts'), 'utf8')
const login = fs.readFileSync(path.join(__dirname, '../app/api/mobile/auth/login/route.ts'), 'utf8')
const web = fs.readFileSync(path.join(__dirname, '../lib/auth.ts'), 'utf8')

test('same canonical Prisma users authenticate web and native, with no second mobile user store', () => {
  assert.match(login, /prisma\.user\.findUnique/)
  assert.match(web, /prisma\.user\.findUnique/)
  assert.match(login, /user\.organizations/)
  assert.match(web, /prisma\.userOrganization\.findMany/)
})
test('production user seed is opt-in, scoped and never resets existing accounts', () => {
  assert.match(script, /process\.argv\.includes\('--apply'\)/)
  assert.match(script, /process\.argv\.includes\('--demo-roles'\)/)
  assert.match(script, /organization\.findUnique/)
  assert.doesNotMatch(script, /user\.upsert/)
  assert.doesNotMatch(script, /user\.update/)
  assert.match(script, /if \(user\) \{/)
  assert.match(script, /bcrypt\.compare/)
  assert.match(script, /notificationPreference\.createMany/)
  assert.match(script, /skipDuplicates: true/)
  assert.match(script, /role: 'member', personaRole: role\.personaRole/)
})
test('demo persona secrets are random, owner-only and never committed as literals', () => {
  assert.match(script, /randomBytes\(36\)\.toString\('base64url'\)/)
  assert.match(script, /mode: 0o600/)
  assert.match(script, /seed\.invalid/)
  assert.doesNotMatch(script, /console\.log\([^\n]*credential\.password/)
})

test('default npm and Prisma seed point to safe dry-run instead of legacy demo data', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'))
  const prismaConfig = fs.readFileSync(path.join(__dirname, '../prisma.config.ts'), 'utf8')
  const legacy = fs.readFileSync(path.join(__dirname, '../prisma/seed.ts'), 'utf8')
  assert.equal(pkg.scripts['db:seed'], 'tsx scripts/seed-shared-users.ts')
  assert.match(prismaConfig, /seed: 'tsx scripts\/seed-shared-users\.ts'/)
  assert.match(legacy, /CORTEX_ALLOW_LEGACY_DEMO_SEED/)
})
