const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const read = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')

test('workforce planner reads real company and team assignments, not mockApi/local simulation', () => {
  const page = read('app/workforce/page.tsx')
  for (const uri of ['/api/team', '/api/projects?take=100', '/api/assignments', '/api/mobile/auth/me']) assert.ok(page.includes(uri),uri)
  assert.doesNotMatch(page, /mockApi|localStorage|Assignment updated \(local simulation\)/)
  assert.match(page, /method: existing \? 'DELETE' : 'POST'/)
  assert.match(page, /body: JSON\.stringify\(\{ projectId, memberId: member\.id, role: member\.role \}\)/)
  assert.match(page, /if \(!response\.ok\) throw new Error/)
  assert.match(page, /const refreshed = await fetch\('\/api\/assignments'/)
})

test('workforce planner keeps assignments multi-project and checks role before exposing editing controls', () => {
  const page = read('app/workforce/page.tsx')
  assert.match(page, /\['owner', 'admin'\]/)
  assert.match(page, /user\?\.role === 'project_manager'/)
  assert.match(page, /\{canEdit && <button/)
  assert.match(page, /A team member can belong to multiple projects/)
  assert.match(page, /role="alert"/)
  assert.match(read('app/apps/page.tsx'), /href: '\/workforce'/)
  assert.match(read('app/team/page.tsx'), /href="\/workforce"/)
  const backend = read('app/api/assignments/route.ts')
  assert.match(backend, /await requireOrg\(\)/)
  assert.match(backend, /programmeProjectScope\(auth\.session\)/)
})
