# Cortexx Next.js main app — standalone server for app-router routes
# (primarily /api/cron/*, which the Express API does not implement).
# Uses the pre-built .next/standalone bundle and generates the Prisma client
# inside the image so the native engine matches the Alpine container.
FROM node:22-alpine

# curl is used by the docker healthcheck.
RUN apk add --no-cache curl

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3010
ENV HOSTNAME=0.0.0.0

WORKDIR /app

# Copy the pre-built standalone server (includes .next/server, node_modules for
# most deps, and static/public assets). Must be generated by `next build` first.
COPY .next/standalone ./

# Prisma client is not included in Next.js standalone output. Bring the schema
# and install only the minimal runtime deps needed to generate it.
COPY prisma/schema.prisma ./prisma/schema.prisma
# Prisma CLI needs DATABASE_URL to load the config, even though `prisma generate`
# only produces the client and does not connect. Use a harmless placeholder.
RUN export DATABASE_URL=postgresql://placeholder:placeholder@localhost:5432/placeholder \
    && npm install --omit=dev --no-save prisma @prisma/client pg \
    && npx prisma generate \
    && npm cache clean --force

EXPOSE 3010

CMD ["node", "server.js"]
