#!/bin/bash
# CortexBuild Ultimate - SSH Key Setup for VPS
# Run this script ONCE on the VPS (via Hostinger web console or password SSH)
# to install the CI/CD SSH public key and disable password authentication.
#
# After running this script, add the private key (id_ed25519_vps) as the
# GitHub secret VPS_SSH_KEY in:
#   Settings → Secrets and variables → Actions → New repository secret

set -euo pipefail

readonly VPS_IP="72.62.132.43"
readonly AUTH_KEYS="/root/.ssh/authorized_keys"
readonly CI_PUBLIC_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL/1Bpko4Ve1Fh9eSmy4Dhp/m7Jfh5+bfqxw9mRUmmMC ci@cortexbuildpro"

echo "=== CortexBuild VPS SSH Key Setup ==="
echo "VPS: $VPS_IP"
echo ""

# Create .ssh directory
mkdir -p /root/.ssh
chmod 700 /root/.ssh

# Add CI public key if not already present
if grep -qF "$CI_PUBLIC_KEY" "$AUTH_KEYS" 2>/dev/null; then
  echo "✅ CI public key already present in authorized_keys"
else
  echo "$CI_PUBLIC_KEY" >> "$AUTH_KEYS"
  chmod 600 "$AUTH_KEYS"
  echo "✅ CI public key added to $AUTH_KEYS"
fi

# Harden SSH config: disable password auth, keep key auth
SSHD_CONF="/etc/ssh/sshd_config"
cp "$SSHD_CONF" "${SSHD_CONF}.bak.$(date +%Y%m%d_%H%M%S)"

# Apply settings idempotently
apply_ssh_setting() {
  local key="$1" value="$2"
  if grep -qE "^#?[[:space:]]*${key}[[:space:]]" "$SSHD_CONF"; then
    sed -i "s|^#*[[:space:]]*${key}[[:space:]].*|${key} ${value}|" "$SSHD_CONF"
  else
    echo "${key} ${value}" >> "$SSHD_CONF"
  fi
}

apply_ssh_setting PubkeyAuthentication yes
apply_ssh_setting AuthorizedKeysFile ".ssh/authorized_keys"
apply_ssh_setting PasswordAuthentication no
apply_ssh_setting PermitRootLogin prohibit-password

echo "✅ sshd_config hardened (PubkeyAuthentication=yes, PasswordAuthentication=no)"

# Reload SSH daemon
if systemctl is-active --quiet sshd; then
  systemctl reload sshd
  echo "✅ sshd reloaded"
elif systemctl is-active --quiet ssh; then
  systemctl reload ssh
  echo "✅ ssh reloaded"
else
  echo "⚠️  Could not reload sshd — restart SSH service manually if needed"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Verify SSH key login works BEFORE closing this session:"
echo "       ssh -i ~/.ssh/id_ed25519_vps root@$VPS_IP 'echo OK'"
echo ""
echo "  2. Add the private key as a GitHub Actions secret:"
echo "       Secret name : VPS_SSH_KEY"
echo "       Secret value: contents of ~/.ssh/id_ed25519_vps"
echo "       (The key was generated by deploy/setup-ssh-key.sh on the CI side)"
echo ""
echo "  3. Remove the old VPS_PASSWORD secret from GitHub Actions if present."
