import { randomUUID } from "node:crypto";
import type { Mission, Task } from "../../core/src/types.js";
import { AgentRegistry } from "./agentRegistry.js";
import { EventBus } from "./eventBus.js";
import { MemoryStore } from "./memory.js";
import { ModelRouter } from "./modelRouter.js";

export class Orchestrator {
  missions=new Map<string,Mission>(); tasks=new Map<string,Task>();
  constructor(public agents:AgentRegistry, public events:EventBus, public memory:MemoryStore, public models:ModelRouter){}
  createMission(goal:string){ const now=new Date().toISOString(); const m:Mission={id:randomUUID(),goal,status:"queued",createdAt:now,updatedAt:now,taskIds:[],budget:{maxSteps:24,maxRetries:3,maxCloudCalls:4}}; this.missions.set(m.id,m); this.events.publish("mission.created",{missionId:m.id,payload:{goal}}); return m; }
  private planFor(goal:string){ const lower=goal.toLowerCase(); const capabilities:string[]=[]; if(/tender|bid/.test(lower)) capabilities.push("tender-research"); if(/supplier|procure|rfq/.test(lower)) capabilities.push("procurement"); if(/code|build|app|software|repo/.test(lower)) capabilities.push("code","verify"); if(/research|market|find|analyse|analyze/.test(lower)) capabilities.push("research"); if(/contract|document|pdf/.test(lower)) capabilities.push("documents"); if(/safety|incident|rams/.test(lower)) capabilities.push("safety"); if(!capabilities.length) capabilities.push("plan","verify"); return [...new Set(capabilities)]; }
  async runMission(id:string){ const m=this.missions.get(id); if(!m) throw new Error("Mission not found"); m.status="planning"; m.updatedAt=new Date().toISOString(); this.events.publish("mission.started",{missionId:id}); const caps=this.planFor(m.goal); this.events.publish("plan.created",{missionId:id,payload:{capabilities:caps}});
    let previous:string|undefined; for(const capability of caps){ const t:Task={id:randomUUID(),missionId:id,title:`${capability}: ${m.goal.slice(0,70)}`,description:m.goal,capability,status:"queued",dependsOn:previous?[previous]:[],retries:0,maxRetries:2}; const agent=this.agents.find(capability); if(agent)t.assignedAgentId=agent.id; this.tasks.set(t.id,t);m.taskIds.push(t.id);previous=t.id;this.events.publish("task.created",{missionId:id,taskId:t.id,payload:{capability}});if(agent)this.events.publish("agent.assigned",{missionId:id,taskId:t.id,agentId:agent.id}); }
    m.status="running"; for(const tid of m.taskIds){ const t=this.tasks.get(tid)!; if(t.dependsOn.some(d=>this.tasks.get(d)?.status!=="completed")){t.status="blocked";continue;} await this.executeTask(m,t); if(t.status==="failed"){m.status="failed";m.error=t.error;this.events.publish("mission.failed",{missionId:id,payload:{error:t.error}});return m;} }
    m.status="verifying"; m.result=m.taskIds.map(x=>this.tasks.get(x)?.result).filter(Boolean).join("\n\n"); m.status="completed";m.updatedAt=new Date().toISOString();this.memory.add({type:"episodic",scope:`mission:${m.id}`,content:`Goal: ${m.goal}\nResult: ${m.result}`,source:"orchestrator",importance:.8,missionId:m.id,tags:["mission","completed"]});this.events.publish("mission.completed",{missionId:id,payload:{result:m.result}});return m;
  }
  private async executeTask(m:Mission,t:Task){ t.status="running";this.events.publish("task.started",{missionId:m.id,taskId:t.id,agentId:t.assignedAgentId});this.agents.setState(t.assignedAgentId||"","busy"); try { const response=await this.models.route({prompt:`Mission: ${m.goal}\nTask capability: ${t.capability}\nReturn a concise, actionable result.`,system:"You are a specialist agent inside Cortex Agent OS. Be accurate, explicit about uncertainty, and produce useful work.",complexity:t.capability==="plan"?4:6}); t.result=response.text||`Task ${t.capability} completed`;t.status="completed";this.memory.add({type:"working",scope:`mission:${m.id}`,content:t.result,source:`agent:${t.assignedAgentId}`,missionId:m.id,taskId:t.id,agentId:t.assignedAgentId,tags:[t.capability]});this.events.publish("task.completed",{missionId:m.id,taskId:t.id,agentId:t.assignedAgentId,payload:{provider:response.provider,model:response.model}});} catch(e){t.retries++;t.error=e instanceof Error?e.message:String(e);t.status="failed";this.events.publish("task.failed",{missionId:m.id,taskId:t.id,agentId:t.assignedAgentId,payload:{error:t.error}});} finally {this.agents.setState(t.assignedAgentId||"","idle");} }
  listMissions(){return [...this.missions.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
  mission(id:string){ const m=this.missions.get(id); return m?{...m,tasks:m.taskIds.map(x=>this.tasks.get(x))}:undefined; }
}
