require_relative '../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# cache invalidation every time a new version of Capacitor is used
def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end


# Xcode Cloud currently requires iOS 15+. Some Capacitor 6 plugin podspecs
# still declare iOS 13, which causes archive validation to fail even though
# the app target and Podfile are already on 15. Raise only lower Pod targets.
post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if current && current.to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
