import React, { useEffect, useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ActivityIndicator, Alert, Modal, ScrollView, TextInput, RefreshControl } from 'react-native';
import { Colors } from './theme';
import { getCollection, getProjects, postCollection } from './api';

const TYPES = ['near_miss', 'first_aid', 'accident', 'dangerous_occurrence', 'environmental', 'security'];
const SEVERITIES = ['near_miss', 'low', 'medium', 'high', 'critical'];

type Incident = { id: string; title: string; type: string; severity: string; status: string; occurredAt: string; project?: { name?: string }; riddorStatus?: string };

export default function SafetyScreen({ onLogout }: { onLogout: () => void }) {
  const [items, setItems] = useState<Incident[]>([]); const [projects, setProjects] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [saving, setSaving] = useState(false); const [err, setErr] = useState('');
  const [form, setForm] = useState({ title: '', description: '', type: 'near_miss', severity: 'low', projectId: '', location: '', immediateActions: '' });
  const load = async () => { setLoading(true); setErr(''); try { const [s,p] = await Promise.all([getCollection('safety', 100), getProjects()]); setItems((s || []) as Incident[]); setProjects(p || []); } catch(e:any){ setErr(e?.message || 'Failed'); if(e?.message==='unauthorized') onLogout(); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const open = () => { setForm({ title:'',description:'',type:'near_miss',severity:'low',projectId:projects[0]?.id || '',location:'',immediateActions:'' }); setModal(true); };
  const save = async () => { if(!form.title.trim()){ Alert.alert('Missing','Describe what happened.'); return; } setSaving(true); try { const r = await postCollection('safety',{...form,title:form.title.trim(),description:form.description.trim()||undefined,location:form.location.trim()||undefined,immediateActions:form.immediateActions.trim()||undefined,occurredAt:new Date().toISOString()}); setModal(false); Alert.alert(r?._queued?'Queued offline':'Incident logged',r?._queued?'Will sync when connection returns.':'Safety record created.'); await load(); } catch(e:any){ Alert.alert('Safety report failed',e?.message||'Please retry.'); } finally { setSaving(false); } };
  return <View style={styles.wrap}><View style={styles.header}><View><Text style={styles.h1}>Safety</Text><Text style={styles.sub}>Report immediately · investigate in web/PM workflow</Text></View><TouchableOpacity onPress={open}><Text style={styles.add}>+ Incident</Text></TouchableOpacity></View>{err?<Text style={styles.err}>{err}</Text>:null}{loading?<View style={styles.center}><ActivityIndicator color={Colors.amber}/></View>:<ScrollView refreshControl={<RefreshControl tintColor={Colors.amber} refreshing={loading} onRefresh={load}/>}>{items.map(i=><View key={i.id} style={[styles.card,(i.severity==='high'||i.severity==='critical')&&{borderColor:Colors.red}]}><View style={styles.between}><Text style={styles.title}>{i.title}</Text><Text style={[styles.badge,{color:i.status==='closed'?Colors.green:Colors.amber}]}>{i.status}</Text></View><Text style={styles.meta}>{i.type.replaceAll('_',' ')} · {i.severity} · {i.project?.name||'No project'}</Text>{i.riddorStatus&&i.riddorStatus!=='not_assessed'?<Text style={styles.riddor}>RIDDOR: {i.riddorStatus.replaceAll('_',' ')}</Text>:null}</View>)}</ScrollView>}
  <Modal visible={modal} transparent animationType="slide"><View style={styles.back}><View style={styles.modal}><Text style={styles.modalTitle}>Report incident</Text><ScrollView><Field label="What happened? *"><TextInput style={styles.input} value={form.title} onChangeText={v=>setForm({...form,title:v})} placeholder="Short incident title" placeholderTextColor={Colors.t3}/></Field><Field label="Description"><TextInput multiline style={[styles.input,{minHeight:80}]} value={form.description} onChangeText={v=>setForm({...form,description:v})} placeholder="Facts only" placeholderTextColor={Colors.t3}/></Field><Field label="Type"><Chips values={TYPES} value={form.type} setValue={v=>setForm({...form,type:v})}/></Field><Field label="Severity"><Chips values={SEVERITIES} value={form.severity} setValue={v=>setForm({...form,severity:v})}/></Field><Field label="Project"><View style={styles.chips}>{projects.map(p=><Chip key={p.id} text={p.name} on={form.projectId===p.id} press={()=>setForm({...form,projectId:p.id})}/>)}</View></Field><Field label="Location"><TextInput style={styles.input} value={form.location} onChangeText={v=>setForm({...form,location:v})} placeholder="Level / elevation / area" placeholderTextColor={Colors.t3}/></Field><Field label="Immediate actions"><TextInput multiline style={[styles.input,{minHeight:70}]} value={form.immediateActions} onChangeText={v=>setForm({...form,immediateActions:v})} placeholder="Area made safe, work stopped…" placeholderTextColor={Colors.t3}/></Field></ScrollView><View style={styles.actions}><TouchableOpacity style={styles.cancel} onPress={()=>setModal(false)}><Text style={{color:Colors.t2}}>Cancel</Text></TouchableOpacity><TouchableOpacity style={styles.save} onPress={save} disabled={saving}><Text style={{color:Colors.ink,fontWeight:'800'}}>{saving?'Saving…':'Report'}</Text></TouchableOpacity></View></View></View></Modal>
  </View>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{marginBottom:12}}><Text style={styles.label}>{label}</Text>{children}</View>}
function Chip({text,on,press}:{text:string;on:boolean;press:()=>void}){return <TouchableOpacity style={[styles.chip,on&&styles.chipOn]} onPress={press}><Text style={[styles.chipText,on&&styles.chipTextOn]}>{text.replaceAll('_',' ')}</Text></TouchableOpacity>}
function Chips({values,value,setValue}:{values:string[];value:string;setValue:(v:string)=>void}){return <View style={styles.chips}>{values.map(v=><Chip key={v} text={v} on={v===value} press={()=>setValue(v)}/>)}</View>}
const styles=StyleSheet.create({wrap:{flex:1,backgroundColor:Colors.ink,padding:20},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},h1:{color:Colors.t1,fontSize:24,fontWeight:'800'},sub:{color:Colors.t3,fontSize:11,marginTop:2,maxWidth:230},add:{color:Colors.red,fontWeight:'800'},err:{color:Colors.red},center:{flex:1,alignItems:'center',justifyContent:'center'},card:{backgroundColor:Colors.ink3,borderWidth:1,borderColor:Colors.hair,borderRadius:12,padding:14,marginBottom:9},between:{flexDirection:'row',justifyContent:'space-between',gap:8},title:{color:Colors.t1,fontSize:15,fontWeight:'700',flex:1},badge:{fontSize:10,fontWeight:'800',textTransform:'uppercase'},meta:{color:Colors.t2,fontSize:11,marginTop:5,textTransform:'capitalize'},riddor:{color:Colors.orange,fontSize:10,fontWeight:'700',marginTop:4,textTransform:'uppercase'},back:{flex:1,backgroundColor:'rgba(2,8,18,.75)',justifyContent:'flex-end'},modal:{backgroundColor:Colors.ink2,padding:20,borderTopLeftRadius:20,borderTopRightRadius:20,maxHeight:'92%'},modalTitle:{color:Colors.t1,fontSize:20,fontWeight:'800',marginBottom:14},label:{color:Colors.t2,fontSize:12,fontWeight:'700',marginBottom:6},input:{backgroundColor:Colors.ink3,borderWidth:1,borderColor:Colors.hair,borderRadius:10,padding:11,color:Colors.t1},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:Colors.ink3,borderWidth:1,borderColor:Colors.hair,borderRadius:16,paddingHorizontal:10,paddingVertical:7},chipOn:{backgroundColor:Colors.amber,borderColor:Colors.amber},chipText:{color:Colors.t2,fontSize:11,textTransform:'capitalize'},chipTextOn:{color:Colors.ink,fontWeight:'800'},actions:{flexDirection:'row',gap:10,marginTop:8},cancel:{flex:1,padding:13,borderRadius:11,borderWidth:1,borderColor:Colors.hair,alignItems:'center'},save:{flex:1,padding:13,borderRadius:11,backgroundColor:Colors.red,alignItems:'center'}});
